# GPU-enabled Docker Compose configuration
# Usage: docker-compose -f docker-compose.yml -f docker-compose.gpu.yml up
version: '3.8'

services:
  manticore:
    environment:
      # Additional GPU settings
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    # Runtime for NVIDIA GPU support
    runtime: nvidia

  web-service:
    environment:
      # Enable GPU acceleration for embeddings if supported
      - MANTICORE_AI_USE_GPU=true
      - CUDA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    # Runtime for NVIDIA GPU support  
    runtime: nvidia