services:
  manticore:
    image: manticoresearch/manticore
    container_name: manticore-search
    ports:
      - "9306:9306"  # SQL port
      - "9308:9308"  # HTTP port
    volumes:
      - manticore_data:/var/lib/manticore
    environment:
      - EXTRA=1
    # Network optimizations for stability
    sysctls:
      - net.core.somaxconn=1024
      - net.ipv4.tcp_keepalive_time=600
      - net.ipv4.tcp_keepalive_intvl=60
      - net.ipv4.tcp_keepalive_probes=3
    healthcheck:
      test: ["CMD-SHELL", "mysql -h0 -P9306 -e 'SHOW TABLES;' || exit 1"]
      interval: 15s  # Increased from 10s
      timeout: 10s   # Increased from 5s
      retries: 10    # Increased from 5
      start_period: 45s # Increased from 30s

  web-service:
    build: .
    container_name: manticore-web-service
    ports:
      - "8080:8080"
    depends_on:
      manticore:
        condition: service_healthy
    volumes:
      - ./data:/app/data:ro
    environment:
      - MANTICORE_HOST=manticore:9308
      - PORT=8080
      - DATA_DIR=/app/data
    restart: unless-stopped

volumes:
  manticore_data: